Fix restoration of stdin flags after using shell
The shell command mucks with stdin to manage polling the remote api
while looking for keystrokes.  It was neglecting to restore all the
flags of the file after exiting which in some cases caused:

   BlockingIOError: [Errno 35] write could not complete without blocking